### ISSUE TITLE
首页下拉刷新无效

### ISSUE THREAD

**Issue by tolking** [airdb/mgmt#57]
组件 NavBar 的设计不是很合理，不应该包含列表在其中。拆分 NavBar 组件才能够更方便地实现下拉刷新

**Comment by deancn** [comment]
@tolking 可以认领这个issue吗

**Comment by tolking** [comment]
> @tolking 可以认领这个issue吗

当然可以

**Comment by bobohuochai** [comment]
把这个任务assign 给你了。@tolking

**Comment by bobohuochai** [comment]
请求参数 没有带上keywords，todo 等后端完善

**Comment by bobohuochai** [comment]
@tolking

**Comment by bobohuochai** [comment]
等待后端完善
